import { UserProvider } from "src/context/authContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { ChateContextProvider } from "src/context/chatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chatty Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ChateContextProvider>{children}</ChateContextProvider>
        </UserProvider>
      </body>
    </html>
  );
}
